version: '3.8'
services:
  web:
    build:
      context: ./packages/web
    volumes:
      - ./packages/web:/app
      #- /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

  core:
    build:
      context: ./packages/core
    volumes:
      - ./packages/core:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: npm run dev
